### ISSUE TITLE
关于辅助音个数设置

### ISSUE THREAD

**Issue by ajin-ajinna** [functoreality/rime-flypy-zrmfast#27]
首先感谢作者的方案，已经十分符合我的需求了，但是我在使用中需要有一项设置，在经过一系列摸索以后还是没有解决，在配置文件中也不知道该修改哪个文件，所以特地来询问一下作者。
问题描述：
        在目前的使用中，在打出一个辅助音以后基本第一个候选字/词就是我要输入的，在我输入下一个词时就需要加一个分号。对于我而言，输入时只识别第三个字母是否为辅助音就足够了
**需求：**辅助音个数从2设置为1
希望能够得到作者的帮助，谢谢

**Comment by functoreality** [comment]
这个应该是可以用拼写运算把辅助码里面多出来的部分去掉。`flypy_zrmfast.custom.yaml` 提供的常用配置项里面没有，可以试试往里面加这两行（或者三行）内容，看看能不能满足要求：
```yaml
patch:
  # ...  # 已经存在的内容
  speller/algebra/+:
    - erase/^..[[]..+$/  # 这一行的作用是删除所有辅助码部分长为 2 或更多的那些编码
    #- xform/[[]//  # 如果之前启用了“直接引导辅助码”，现在是取消这一行的注释，把原来的那行设置去掉
```
我从你的描述里推测你可能是开了“直接引导辅助码”，这个选项之前是通过 `speller/algebra/@next: xform/[[]//` 这一句实现的，现在需要把这一行设置去掉（或者注释掉）。
